// <auto-generated />
using System;
using DatabaseProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.SubjectEntities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentType", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpectedGroupsCountForEleventhClasses")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedGroupsCountForTenthClasses")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedHoursPerWeekForEleventhClasses")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedHoursPerWeekForTenthClasses")
                        .HasColumnType("int");

                    b.Property<bool>("IsEge")
                        .HasColumnType("bit");

                    b.Property<int>("NotebooksPaymentInPercents")
                        .HasColumnType("int");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SubjectCategoryId");

                    b.HasIndex("SubjectTypeId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SubjectCategory", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SubjectType", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.ContractType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContractType", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherEducation", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdvancedSubjectsAffectOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ContractTypeAffectsOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<bool>("EgeAffectsOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperienceInYearsOnEmploymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsClassTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("TeacherCategoryAffectsOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TeacherCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("EducationId");

                    b.HasIndex("TeacherCategoryId");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.TeacherCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeacherCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherCategory", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.LessonEntities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassStudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Classroom")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorizontalSubgroupStudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("LessonType")
                        .HasColumnType("int");

                    b.Property<int?>("LiceumStudentGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ParallelStudentGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentGroupType")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("VerticalSubgroupStudentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassStudentGroupId");

                    b.HasIndex("HorizontalSubgroupStudentGroupId");

                    b.HasIndex("LiceumStudentGroupId");

                    b.HasIndex("ParallelStudentGroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("VerticalSubgroupStudentGroupId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ClassStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassStudentGroup");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.HorizontalSubgroupStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HorizontalSubgroupStudentGroup", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.LiceumStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("LiceumStudentGroup", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ParallelStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParallelStudentGroup", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.VerticalSubgroupStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VerticalSubgroupStudentGroup", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.Subject", b =>
                {
                    b.HasOne("Domain.SubjectEntities.PaymentType", "PaymentType")
                        .WithMany("Subjects")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SubjectEntities.SubjectCategory", "SubjectCategory")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SubjectEntities.SubjectType", "SubjectType")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("SubjectCategory");

                    b.Navigation("SubjectType");
                });

            modelBuilder.Entity("Domain.TeacherEntities.Teacher", b =>
                {
                    b.HasOne("Domain.TeacherEntities.ContractType", "ContractType")
                        .WithMany("Teachers")
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Education", "Education")
                        .WithMany("Teachers")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.TeacherCategory", "TeacherCategory")
                        .WithMany("Teachers")
                        .HasForeignKey("TeacherCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContractType");

                    b.Navigation("Education");

                    b.Navigation("TeacherCategory");
                });

            modelBuilder.Entity("Domain.TimetableEntities.LessonEntities.Lesson", b =>
                {
                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.ClassStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ClassStudentGroupId");

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.HorizontalSubgroupStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("HorizontalSubgroupStudentGroupId");

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.LiceumStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("LiceumStudentGroupId");

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.ParallelStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ParallelStudentGroupId");

                    b.HasOne("Domain.SubjectEntities.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.VerticalSubgroupStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("VerticalSubgroupStudentGroupId");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.SubjectEntities.PaymentType", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.SubjectEntities.Subject", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectCategory", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectType", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.TeacherEntities.ContractType", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.TeacherEntities.Education", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.TeacherEntities.Teacher", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TeacherEntities.TeacherCategory", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ClassStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.HorizontalSubgroupStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.LiceumStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ParallelStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.VerticalSubgroupStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
