// <auto-generated />
using System;
using DatabaseProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AssignmentEntities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<int>("GroupCount")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.CourceTeachers.CourseTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthdayDate")
                        .HasColumnType("date");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CourseTeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EmploymentDate")
                        .HasColumnType("date");

                    b.Property<int>("ExperienceInYearsOnEmploymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.ToTable("CourseTeacher", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.CourceTeachers.CourseTeacherAvailableHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseTeacherId");

                    b.ToTable("CourseTeacherAvailableHours", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseAssignments.CourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CourseTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("GroupCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseTeacherId");

                    b.ToTable("CourseAssignment", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CoursesEducationalPlan", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlanHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursesEducationalPlanId")
                        .HasColumnType("int");

                    b.Property<int>("HoursCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CoursesEducationalPlanId");

                    b.ToTable("CoursesEducationalPlanHours", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseTimetables.CourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classroom")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CourseTeacherId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LessonType")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("StudentGroupNumber")
                        .HasColumnType("int");

                    b.Property<int>("StudentGroupType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseTeacherId");

                    b.ToTable("CourseLesson", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseEducationalPlanId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedGroupsCount")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedHoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseTypeId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Domain.CourseEntities.Courses.CourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourseType", (string)null);
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EducationalPlan", (string)null);
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlanHoursByWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationalPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("EducationalPlanSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("HoursCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EducationalPlanId");

                    b.HasIndex("EducationalPlanSubjectId");

                    b.ToTable("EducationalPlanHoursByWeek", (string)null);
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlanSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EducationalPlanId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationalPlanId");

                    b.HasIndex("SubjectId");

                    b.ToTable("EducationalPlanSubject", (string)null);
                });

            modelBuilder.Entity("Domain.ReportEntities.SubdeanEntities.MonthComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("MonthComment", (string)null);
                });

            modelBuilder.Entity("Domain.ReportEntities.SubdeanEntities.YearComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("YearComment", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentType", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpectedGroupsCountForEleventhClasses")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedGroupsCountForTenthClasses")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedHoursPerWeekForEleventhClasses")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedHoursPerWeekForTenthClasses")
                        .HasColumnType("int");

                    b.Property<bool>("IsEge")
                        .HasColumnType("bit");

                    b.Property<int>("NotebooksPaymentInPercents")
                        .HasColumnType("int");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SubjectCategoryId");

                    b.HasIndex("SubjectTypeId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SubjectCategory", (string)null);
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SubjectType", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.ContractType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContractType", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherEducation", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdvancedSubjectsAffectOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("BirthdayDate")
                        .HasColumnType("date");

                    b.Property<bool>("ContractTypeAffectsOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<bool>("EgeAffectsOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("EmploymentDate")
                        .HasColumnType("date");

                    b.Property<int>("ExperienceInYearsOnEmploymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsClassTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("TeacherCategoryAffectsOnSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TeacherCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("EducationId");

                    b.HasIndex("TeacherCategoryId");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("Domain.TeacherEntities.TeacherCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeacherCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherCategory", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.GuidebookEntities.LessonTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseTeacherAvailableHoursId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseTeacherAvailableHoursId");

                    b.ToTable("LessonTime", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.GuidebookEntities.PairTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseTeacherAvailableHoursId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseTeacherAvailableHoursId");

                    b.ToTable("PairTime", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.GuidebookEntities.ParadeTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParadeTime", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.LessonEntities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassStudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Classroom")
                        .HasColumnType("int");

                    b.Property<int>("CurrentGroup")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("HorizontalSubgroupStudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("LessonType")
                        .HasColumnType("int");

                    b.Property<int?>("LiceumStudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGroups")
                        .HasColumnType("int");

                    b.Property<string>("ParadeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParallelStudentGroupId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("StudentGroupGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentGroupType")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("VerticalSubgroupStudentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassStudentGroupId");

                    b.HasIndex("HorizontalSubgroupStudentGroupId");

                    b.HasIndex("LiceumStudentGroupId");

                    b.HasIndex("ParallelStudentGroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("VerticalSubgroupStudentGroupId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ClassStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassStudentGroup");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.HorizontalSubgroupStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HorizontalSubgroupStudentGroup");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.LiceumStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LiceumStudentGroup");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ParallelStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParallelStudentGroup");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.VerticalSubgroupStudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parallel")
                        .HasColumnType("int");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VerticalSubgroupStudentGroup");
                });

            modelBuilder.Entity("Domain.TimetableEntities.TeacherEntities.TeacherAvailableHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAvailableHours", (string)null);
                });

            modelBuilder.Entity("LessonTimeTeacherAvailableHours", b =>
                {
                    b.Property<int>("AvailableLessonTimesId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherAvailableHoursId")
                        .HasColumnType("int");

                    b.HasKey("AvailableLessonTimesId", "TeacherAvailableHoursId");

                    b.HasIndex("TeacherAvailableHoursId");

                    b.ToTable("LessonTimeTeacherAvailableHours");
                });

            modelBuilder.Entity("PairTimeTeacherAvailableHours", b =>
                {
                    b.Property<int>("AvailablePairTimesId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherAvailableHoursId")
                        .HasColumnType("int");

                    b.HasKey("AvailablePairTimesId", "TeacherAvailableHoursId");

                    b.HasIndex("TeacherAvailableHoursId");

                    b.ToTable("PairTimeTeacherAvailableHours");
                });

            modelBuilder.Entity("Domain.AssignmentEntities.Assignment", b =>
                {
                    b.HasOne("Domain.SubjectEntities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourceTeachers.CourseTeacher", b =>
                {
                    b.HasOne("Domain.TeacherEntities.ContractType", "ContractType")
                        .WithMany("CourseTeachers")
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContractType");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourceTeachers.CourseTeacherAvailableHours", b =>
                {
                    b.HasOne("Domain.CourseEntities.CourceTeachers.CourseTeacher", "CourseTeacher")
                        .WithMany("AvailableHours")
                        .HasForeignKey("CourseTeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseTeacher");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseAssignments.CourseAssignment", b =>
                {
                    b.HasOne("Domain.CourseEntities.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.CourseEntities.CourceTeachers.CourseTeacher", "CourseTeacher")
                        .WithMany()
                        .HasForeignKey("CourseTeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseTeacher");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlan", b =>
                {
                    b.HasOne("Domain.CourseEntities.Courses.Course", "Course")
                        .WithOne("CourseEducationalPlan")
                        .HasForeignKey("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlan", "CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlanHours", b =>
                {
                    b.HasOne("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlan", "CoursesEducationalPlan")
                        .WithMany("CoursesEducationalPlanHours")
                        .HasForeignKey("CoursesEducationalPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CoursesEducationalPlan");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseTimetables.CourseLesson", b =>
                {
                    b.HasOne("Domain.CourseEntities.Courses.Course", "Course")
                        .WithMany("CourseLessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.CourseEntities.CourceTeachers.CourseTeacher", "CourseTeacher")
                        .WithMany("CourseLessons")
                        .HasForeignKey("CourseTeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseTeacher");
                });

            modelBuilder.Entity("Domain.CourseEntities.Courses.Course", b =>
                {
                    b.HasOne("Domain.CourseEntities.Courses.CourseType", "CourseType")
                        .WithMany("Courses")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseType");
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlanHoursByWeek", b =>
                {
                    b.HasOne("Domain.EducationalPlan.EducationalPlan", "EducationalPlan")
                        .WithMany()
                        .HasForeignKey("EducationalPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.EducationalPlan.EducationalPlanSubject", null)
                        .WithMany("EducationalPlanHours")
                        .HasForeignKey("EducationalPlanSubjectId");

                    b.Navigation("EducationalPlan");
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlanSubject", b =>
                {
                    b.HasOne("Domain.EducationalPlan.EducationalPlan", null)
                        .WithMany("Subjects")
                        .HasForeignKey("EducationalPlanId");

                    b.HasOne("Domain.SubjectEntities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.ReportEntities.SubdeanEntities.MonthComment", b =>
                {
                    b.HasOne("Domain.SubjectEntities.PaymentType", "PaymentType")
                        .WithMany("MonthComments")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Teacher", "Teacher")
                        .WithMany("MonthComments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.ReportEntities.SubdeanEntities.YearComment", b =>
                {
                    b.HasOne("Domain.SubjectEntities.PaymentType", "PaymentType")
                        .WithMany("YearComments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Teacher", "Teacher")
                        .WithMany("YearComments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.SubjectEntities.Subject", b =>
                {
                    b.HasOne("Domain.SubjectEntities.PaymentType", "PaymentType")
                        .WithMany("Subjects")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SubjectEntities.SubjectCategory", "SubjectCategory")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.SubjectEntities.SubjectType", "SubjectType")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("SubjectCategory");

                    b.Navigation("SubjectType");
                });

            modelBuilder.Entity("Domain.TeacherEntities.Teacher", b =>
                {
                    b.HasOne("Domain.TeacherEntities.ContractType", "ContractType")
                        .WithMany("Teachers")
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Education", "Education")
                        .WithMany("Teachers")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.TeacherCategory", "TeacherCategory")
                        .WithMany("Teachers")
                        .HasForeignKey("TeacherCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContractType");

                    b.Navigation("Education");

                    b.Navigation("TeacherCategory");
                });

            modelBuilder.Entity("Domain.TimetableEntities.GuidebookEntities.LessonTime", b =>
                {
                    b.HasOne("Domain.CourseEntities.CourceTeachers.CourseTeacherAvailableHours", null)
                        .WithMany("AvailableLessonTimes")
                        .HasForeignKey("CourseTeacherAvailableHoursId");
                });

            modelBuilder.Entity("Domain.TimetableEntities.GuidebookEntities.PairTime", b =>
                {
                    b.HasOne("Domain.CourseEntities.CourceTeachers.CourseTeacherAvailableHours", null)
                        .WithMany("AvailablePairTimes")
                        .HasForeignKey("CourseTeacherAvailableHoursId");
                });

            modelBuilder.Entity("Domain.TimetableEntities.LessonEntities.Lesson", b =>
                {
                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.ClassStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ClassStudentGroupId");

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.HorizontalSubgroupStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("HorizontalSubgroupStudentGroupId");

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.LiceumStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("LiceumStudentGroupId");

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.ParallelStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("ParallelStudentGroupId");

                    b.HasOne("Domain.SubjectEntities.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TeacherEntities.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.TimetableEntities.StudentGroupEntities.VerticalSubgroupStudentGroup", null)
                        .WithMany("Lessons")
                        .HasForeignKey("VerticalSubgroupStudentGroupId");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.TimetableEntities.TeacherEntities.TeacherAvailableHours", b =>
                {
                    b.HasOne("Domain.TeacherEntities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LessonTimeTeacherAvailableHours", b =>
                {
                    b.HasOne("Domain.TimetableEntities.GuidebookEntities.LessonTime", null)
                        .WithMany()
                        .HasForeignKey("AvailableLessonTimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.TimetableEntities.TeacherEntities.TeacherAvailableHours", null)
                        .WithMany()
                        .HasForeignKey("TeacherAvailableHoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairTimeTeacherAvailableHours", b =>
                {
                    b.HasOne("Domain.TimetableEntities.GuidebookEntities.PairTime", null)
                        .WithMany()
                        .HasForeignKey("AvailablePairTimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.TimetableEntities.TeacherEntities.TeacherAvailableHours", null)
                        .WithMany()
                        .HasForeignKey("TeacherAvailableHoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CourseEntities.CourceTeachers.CourseTeacher", b =>
                {
                    b.Navigation("AvailableHours");

                    b.Navigation("CourseLessons");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourceTeachers.CourseTeacherAvailableHours", b =>
                {
                    b.Navigation("AvailableLessonTimes");

                    b.Navigation("AvailablePairTimes");
                });

            modelBuilder.Entity("Domain.CourseEntities.CourseEducationalPlans.CoursesEducationalPlan", b =>
                {
                    b.Navigation("CoursesEducationalPlanHours");
                });

            modelBuilder.Entity("Domain.CourseEntities.Courses.Course", b =>
                {
                    b.Navigation("CourseEducationalPlan")
                        .IsRequired();

                    b.Navigation("CourseLessons");
                });

            modelBuilder.Entity("Domain.CourseEntities.Courses.CourseType", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlan", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.EducationalPlan.EducationalPlanSubject", b =>
                {
                    b.Navigation("EducationalPlanHours");
                });

            modelBuilder.Entity("Domain.SubjectEntities.PaymentType", b =>
                {
                    b.Navigation("MonthComments");

                    b.Navigation("Subjects");

                    b.Navigation("YearComments");
                });

            modelBuilder.Entity("Domain.SubjectEntities.Subject", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectCategory", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.SubjectEntities.SubjectType", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.TeacherEntities.ContractType", b =>
                {
                    b.Navigation("CourseTeachers");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.TeacherEntities.Education", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.TeacherEntities.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("MonthComments");

                    b.Navigation("YearComments");
                });

            modelBuilder.Entity("Domain.TeacherEntities.TeacherCategory", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ClassStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.HorizontalSubgroupStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.LiceumStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.ParallelStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.TimetableEntities.StudentGroupEntities.VerticalSubgroupStudentGroup", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
