version: '3'

services:
  frontend:
    build: 
      context: frontend/
    container_name: frontend
    restart: always
    ports:
      - "2000:3000"

  backend:
    build: 
      context: BackendSrc/
    container_name: backend
    restart: always
    ports:
      - "81:80"